#!/bin/bash

### BEGIN INIT INFO
# Provides:          aria2
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: High speed download utility
### END INIT INFO

#set -x
ARIA2_USER="victor"

start()
{
    PID=`ps -ef | grep aria2c | grep -v grep | awk '{print $2}'`
    if [ "X${PID}" == "X" ]; then 
        echo "starting aria2c"
        su - ${ARIA2_USER} -c "/usr/bin/aria2c --conf-path=/home/victor/.aria2/aria2.conf >/dev/null 2>&1 -D"
    fi
}

stop()
{
    PID=`ps -ef | grep aria2c | grep -v grep | awk '{print $2}'`
    if [ "X${PID}" != "X" ]; then
        echo "stopping aria2c"
        kill -9 ${PID}
    fi
}

status()
{
    PID=`ps -ef | grep aria2c | grep -v grep | awk '{print $2}'`
    if [ "X${PID}" == "X" ]; then
        echo "aria2c not running"
    else
        echo "aria2c is running PID:  ${PID}"
    fi
}

case $1 in 
    start)
        start
        status
    ;;
    
    stop)
        stop
        status
    ;;
    
    status)
        status
    ;;
    
    restart)
        stop
        start
        status
    ;;
esac

